version: "3"
services:
  mysql8:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      #      - Initialization of script
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      #      - For external access 13318
      - 13318:3306
